import type { NextPage } from 'next'
import Head from 'next/head'
import Starters from '../starters/Starters'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Starter Axies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Starters/>
    </div>
  )
}

export default Home
